#!/bin/sh

yabai -m config external_bar               all:29:0      \
                top_padding                29           \
                mouse_follows_focus        on           \
                focus_follows_mouse        off          \
                window_placement           second_child \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                2            \
                bottom_padding             4            \
                left_padding               4            \
                right_padding              4            \
                window_gap                 4            \
                layout                     bsp


yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Alfred" app="Alfred" title="Alfred" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Kap" app="^Kap$" manage=off
yabai -m rule --add label="Mail" app="Mail" title="Email" manage=off
yabai -m rule --add label="Raycast" app="Raycast" title="Raycast" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Settings" app="^Settings$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="System Information" app="System Information" title="System Information" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="qFlipper" app="qFlipper" title="qFlipper" manage=off

echo "yabai configuration loaded.."
