#!/usr/bin/env lua

-- Shouldn't need this due to having it in an init.lua but leaving in case of migration later.
-- package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Load Helpers
require("helpers")
-- Load Sketchybar
require("init")
