#!/usr/bin/env lua

-- Shouldn't need this due to having it in an init.lua but leaving in case of migration later.
-- package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

print(package.cpath)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

print("Requiring sketchybar")
local sbar = require("sketchybar")

print("Config")
sbar.begin_config()

require("bar")
sbar.hotload(true)
-- Load Items: This calls the items/init.lua which requires all other items.

print("Setting up Sketchybar Items:")
require("items")
require("brackets")

sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- bi-directional communication between the lua module and sketchybar)
-- This must be the last thing in the config, nothing runs after this:
sbar.event_loop()
