hl.on("hyprland.start", function()
	-- hl.exec_cmd("ghostty", { workspace = 1, silent = true })
	-- hl.exec_cmd("zen-browser", { workspace = 7, silent = true })
	-- hl.exec_cmd("discord", { workspace = 8, silent = true })
	-- hl.exec_cmd("signal-desktop", { workspace = 9, silent = true })
end)
