#!/bin/fish

## Meh == lctrl + lalt + shift
## Hyper == lctrl + lalt + shift + lcmd

# Window Navigation (through display borders): lalt - {n, i, e, o}
lalt - n : yabai -m window --focus west || yabai -m display --focus west
lalt - i : yabai -m window --focus south || yabai -m display --focus south
lalt - e : yabai -m window --focus north || yabai -m display --focus north
lalt - o : yabai -m window --focus east || yabai -m display --focus east

# Extended Window Navigation: lalt - {b, k}
lctrl + lalt - b : yabai -m window --focus first
lctrl + lalt - k : yabai -m window --focus last

# Float / Unfloat window: lcmd + shift - v
lcmd + shift - v : yabai -m window --toggle float; sketchybar --trigger window_focus

# Make window zoom to fullscreen: shift + lalt - f
lctrl + shift + lalt - f : yabai -m window --toggle zoom-fullscreen; sketchybar --trigger window_focus

# Toggle split orientation of the selected windows node: shift + lalt - s
shift + lalt - s : yabai -m window --toggle split

# Cannot use due to systemd integ still on.
#shift + lalt - p : yabai -m window --space prev; yabai -m space --focus prev; sketchybar --trigger windows_on_spaces
#shift + lalt - n : yabai -m window --space next; yabai -m space --focus next; sketchybar --trigger windows_on_spaces

# Mirror Space on X and Y Axis: shift + lalt - {x, y}
#shift + lalt - x : yabai -m space --mirror x-axis
#shift + lalt - y : yabai -m space --mirror y-axis

## Misc
# Open new Terminal window
# lalt - t : alacritty msg create-window
lalt - t : wezterm
lalt - b : open -n /Applications/Arc.app

# New window in hor./ vert. splits for all applications with yabai
lalt - s : yabai -m window --insert east; skhd -k "cmd - n"
lalt - v : yabai -m window --insert south; skhd -k "cmd - n"

# Toggle sketchybar
shift + lalt - space : sketchybar --bar hidden=toggle
shift + lalt - r : sketchybar --restart-service
#shift + lalt - r : sketchybar --exit

## Resize (ctrl + lalt - ...)
# Resize windows: ctrl + lalt - {n, i, e, o}
#ctrl + lalt - n    : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
hyper - n : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
hyper - i : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
hyper - e : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
hyper - o : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# Equalize size of windows: ctrl + lalt - e
meh - m : yabai -m space --balance

# Enable / Disable gaps in current workspace: ctrl + lalt - g
meh - g : yabai -m space --toggle padding; yabai -m space --toggle gap

### Navigation (lalt - ...)
# Space Navigation (four spaces per display): lalt - {1, 2, 3, 4}
lalt - 1 : set DISPLAY "$(yabai -m query --displays --display | jq '.index')"; yabai -m space --focus (math (math 1 + 4) * (math $DISPLAY - 1))
lalt - 2 : set DISPLAY "$(yabai -m query --displays --display | jq '.index')"; yabai -m space --focus $((math 2+4 * (math $DISPLAY - 1)))
lalt - 3 : set DISPLAY "$(yabai -m query --displays --display | jq '.index')"; yabai -m space --focus $((3+4*($DISPLAY - 1)))
lalt - 4 : set DISPLAY "$(yabai -m query --displays --display | jq '.index')"; yabai -m space --focus $((4+4*($DISPLAY - 1)))

## Window Movement (shift + lalt - ...)
# Moving windows in spaces: shift + lalt - {n, e, i, o}
#shift + lalt - n : yabai -m window --warp west || yabai -m window --display west && sketchybar --trigger windows_on_spaces && yabai -m display --focus west && yabai -m window --warp last || yabai -m window --move rel:-10:0
#shift + lalt - i : yabai -m window --warp south || yabai -m window --display south && sketchybar --trigger windows_on_spaces && yabai -m display --focus south || yabai -m window --move rel:0:10
#shift + lalt - e : yabai -m window --warp north || yayabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=offbai -m window --display north && sketchybar --trigger windows_on_spaces && yabai -m display --focus north || yabai -m window --move rel:0:-10
#shift + lalt - o : yabai -m window --warp east || yabai -m window --display east && sketchybar --trigger windows_on_spaces && yabai -m display --focus east && yabai -m window --warp first || yabai -m window --move rel:10:00

shift + lalt - n : yabai -m window --warp west || yabai -m window --display west && yabai -m display --focus west && yabai -m window --warp last || yabai -m window --move rel:-10:0
shift + lalt - i : yabai -m window --warp south || yabai -m window --display south && yabai -m display --focus south || yabai -m window --move rel:0:10
shift + lalt - e : yabai -m window --warp north || yabai -m window --display north && yabai -m display --focus north || yabai -m window --move rel:0:-10
shift + lalt - o : yabai -m window --warp east || yabai -m window --display east && yabai -m display --focus east && yabai -m window --warp first || yabai -m window --move rel:10:00

## Stacks (shift + ctrl - ...)
# Add the active window to the window or stack to the {direction}: shift + ctrl - {j, k, l, ö}
shift + ctrl - n : yabai -m window west --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus
shift + ctrl - i : yabai -m window south --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus
shift + ctrl - e : yabai -m window north --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus
shift + ctrl - o : yabai -m window east --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus

# Stack Navigation: shift + ctrl - {n, p}
shift + ctrl - n : yabai -m window --focus stack.next
shift + ctrl - p : yabai -m window --focus stack.prev

# Enable / Disable gaps in current workspace: ctrl + lalt - g

## Insertion (shift + ctrl + lalt - ...)
# Set insertion point for focused container: shift + ctrl + lalt - {n, e, i, o, s}
meh - n : yabai -m window --insert west
meh - i : yabai -m window --insert south
meh - e : yabai -m window --insert north
meh - o : yabai -m window --insert east
meh - s : yabai -m window --insert stack
