# umbral-serenity.conf

background #111119
foreground #dfb7e8

cursor #f1c4e0

selection_background #262440
selection_foreground #ff7ab2

color0  #0b0b14
color1  #d14e7c
color2  #c081fa
color3  #f1c4e0
color4  #6f7ef0
color5  #a048ed
color6  #7aa6ff
color7  #dfb7e8

color8  #35355e
color9  #f72d7c
color10 #c081fa
color11 #fca1e7
color12 #9ca7ff
color13 #c081fa
color14 #9ca7ff
color15 #eed6ee
