#!/usr/bin/env lua

-- Shouldn't need this due to having it in an init.lua but leaving in case of migration later.
-- package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- local pix_bar = require("pix.sketchybar")
local sbar = require("sketchybar")

require("bar")

-- print("Killing the CPU helper and restarting")
-- os.execute("killall helper")
-- os.execute("cd /Users/pix/AdeptusCustodes/pix_hyprland/pixconfig/sketchybar/helper && make")
-- os.execute("/Users/pix/AdeptusCustodes/pix_hyprland/pixconfig/sketchybar/helper git.felix.helper >/dev/null 2>&1 &")

sbar.hotload(true)

-- Load Items: This calls the items/init.lua which requires all other items.
print("Setting up Sketchybar Items:")
require("items")
require("brackets")

-- Run the event loop of the sketchybar module (without this there will be no
-- bi-directional communication between the lua module and sketchybar)
-- This must be the last thing in the config, nothing runs after this:
sbar.event_loop()
